### ISSUE TITLE
Iris does not run

### ISSUE THREAD

**Issue by akiraheid** [akiraheid/Olympus#9]
```
> ./bin/www
STATUS: 200
/home/dev/code/Olympus/nodejs/Iris/routes/tropicalOutlook.js:93
    data[0][0].substring(
           ^
TypeError: Cannot read property '0' of undefined
    at handleNOAARes (/home/dev/code/Olympus/nodejs/Iris/routes/tropicalOutlook.js:93:12)
    at IncomingMessage.<anonymous> (/home/dev/code/Olympus/nodejs/Iris/routes/tropicalOutlook.js:193:9)
    at IncomingMessage.emit (events.js:107:17)
    at IncomingMessage.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickCallback (node.js:355:11)
```

**Comment by akiraheid** [comment]
Resolved with commit 8182786c2e2f7cddd206caa5decc7042673e7c44.
